#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, getopt
import subprocess as subp

def main(argv):
  shortOpts = "p:h"
  longOpts = ["path=", "help"]
  try:
    print "Testing python modules ..."
    optlist, mods = getopt.gnu_getopt(argv, shortOpts, longOpts)
    if len(mods) == 0:
      usage()
      sys.exit(1)
    path = None
    # Parse the given options.
    for opt, arg in optlist:
      if opt in ("-p", "--path"):
        path = arg
      elif opt == "--help":
        usage()
        sys.exit(0)
    if path == None:
      print "CutEr's priv directory has not been specified."
      sys.exit(1)
    # Run tests.
    cmds = ["echo \"{} ...\" && python {}/{}.py".format(mod, path, mod) for mod in mods]
    sys.exit(runCmds(cmds))
  except Exception as e:
    print "Fatal Error:", e
    sys.exit(1)

def runCmds(cmds):
  return 0 if all([subp.call(cmd, shell=True) == 0 for cmd in cmds]) else 1

def usage():
  print "Usage: python_test options Mods"
  print "PARAMETERS"
  print "	Mods				A list of space-separated modules."
  print "OPTIONS"
  print "	-p Dir, --path=Dir		The directory Dir of CutEr's priv."
  print "	--help				Display this information."

if __name__ == "__main__":
  try:
    main(sys.argv[1:])
  except KeyboardInterrupt:
    sys.exit(1)
