#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
outfile=$DIR/$5
expected=$7/$5.expected
ebin=$6

echo "Running ./cuter $1 $2 $3 $4 ..."
cd "$ebin" && $DIR/cuter $1 $2 "$3" $4 > "$outfile"
if diff -q "$outfile" "$expected"; then
  rm -f "$outfile"
  exit 0
else
  echo "Result mismatch ..."
  cat "$outfile"
  rm -f "$outfile"
  exit 1
fi
