#!/usr/bin/env python
# -*- coding: utf-8 -*-

from cuter_global import *

JSON_TYPE_ANY = 0
JSON_TYPE_INT = 1
JSON_TYPE_FLOAT = 2
JSON_TYPE_ATOM = 3
JSON_TYPE_LIST = 4
JSON_TYPE_TUPLE = 5
JSON_TYPE_PID = 6
JSON_TYPE_REF = 7
JSON_TYPE_BITSTRING = 8
JSON_TYPE_FUN = 9

JSON_ERLTYPE_NTUPLE = -2
JSON_ERLTYPE_CONS = -1
JSON_ERLTYPE_ANY = 0
JSON_ERLTYPE_ATOM = 1
JSON_ERLTYPE_ATOMLIT = 2
JSON_ERLTYPE_FLOAT = 3
JSON_ERLTYPE_INTEGER = 4
JSON_ERLTYPE_INTEGERLIT = 5
JSON_ERLTYPE_LIST = 6
JSON_ERLTYPE_NIL = 7
JSON_ERLTYPE_TUPLE = 8
JSON_ERLTYPE_TUPLEDET = 9
JSON_ERLTYPE_UNION = 10
JSON_ERLTYPE_RANGE = 11
JSON_ERLTYPE_NONEMPTY_LIST = 12
JSON_ERLTYPE_BITSTRING = 13
JSON_ERLTYPE_GENERIC_FUN = 14
JSON_ERLTYPE_FUN = 15

CMD_LOAD_TRACE_FILE = 1
CMD_SOLVE = 2
CMD_GET_MODEL = 3
CMD_ADD_AXIOMS = 4
CMD_FIX_VARIABLE = 5
CMD_RESET_SOLVER = 6
CMD_STOP = 42

RSP_MODEL_DELIMITER_START = "model_start"
RSP_MODEL_DELIMITER_END = "model_end"

CONSTRAINT_TRUE = 1
CONSTRAINT_FALSE = 2
NOT_CONSTRAINT = 3

OP_PARAMS = 1
OP_SPEC = 2
OP_LAMBDA = 3
OP_GUARD_TRUE = 4
OP_GUARD_FALSE = 5
OP_MATCH_EQUAL_TRUE = 6
OP_MATCH_EQUAL_FALSE = 7
OP_TUPLE_SZ = 8
OP_TUPLE_NOT_SZ = 9
OP_TUPLE_NOT_TPL = 10
OP_LIST_NON_EMPTY = 11
OP_LIST_EMPTY = 12
OP_LIST_NOT_LST = 13
OP_SPAWN = 14
OP_SPAWNED = 15
OP_MSG_SEND = 16
OP_MSG_RECEIVE = 17
OP_MSG_CONSUME = 18
OP_UNFOLD_TUPLE = 19
OP_UNFOLD_LIST = 20
OP_HD = 21
OP_TL = 22
OP_IS_INTEGER = 23
OP_IS_ATOM = 24
OP_IS_FLOAT = 25
OP_IS_LIST = 26
OP_IS_TUPLE = 27
OP_IS_BOOLEAN = 28
OP_IS_NUMBER = 29
OP_PLUS = 30
OP_MINUS = 31
OP_TIMES = 32
OP_RDIV = 33
OP_IDIV_NAT = 34
OP_REM_NAT = 35
OP_UNARY = 36
OP_EQUAL = 37
OP_UNEQUAL = 38
OP_FLOAT = 39
OP_BOGUS = 40
OP_ATOM_NIL = 41
OP_ATOM_HEAD = 42
OP_ATOM_TAIL = 43
OP_LIST_TO_TUPLE = 44
OP_TUPLE_TO_LIST = 45
OP_LT_INT = 46
OP_LT_FLOAT = 47
OP_CONS = 48
OP_TCONS = 49
OP_POW = 50
OP_MAKE_BITSTR = 51
OP_EMPTY_BITSTR = 52
OP_NONEMPTY_BITSTR = 53
OP_CONCAT_SEGS = 54
OP_BITMATCH_CONST_TRUE = 55
OP_BITMATCH_CONST_FALSE = 56
OP_BITMATCH_VAR_TRUE = 57
OP_BITMATCH_VAR_FALSE = 58
OP_IS_BITSTRING = 59
OP_IS_FUN = 60
OP_IS_FUN_WITH_ARITY = 61
OP_NOT_LAMBDA_WITH_ARITY = 62
OP_FRESH_LAMBDA_WITH_ARITY = 63
OP_EVALUATED_CLOSURE = 64
OP_TRUNC = 65
OP_BAND = 66
OP_BXOR = 67
OP_BOR = 68

SOLVER_STATUS_SAT = "sat"
SOLVER_STATUS_UNSAT = "unsat"
SOLVER_STATUS_UNKNOWN = "unknown"
SOLVER_STATUS_TIMEOUT = "timeout"

def is_constraint_kind(tp):
  return tp == CONSTRAINT_TRUE or tp == CONSTRAINT_FALSE

def is_interpretable(tp):
  xs = set([OP_SPAWN, OP_SPAWNED, OP_MSG_SEND, OP_MSG_RECEIVE, OP_MSG_CONSUME])
  return tp not in xs

def is_reversible(tp, opcode):
  return is_constraint_kind(tp)
