name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  otps:
    name: OTP ${{ matrix.otp }}
    runs-on: ubuntu-latest
    container: aggelgian/erlang:${{ matrix.otp }}
    strategy:
      matrix:
        otp:
          - "22.3"
          - "21.3"
          - "21.0"
          - "20.3"
    env:
      GPB_ALLOW_NON_CONFORMING_VSN_FORMAT: 1
      Z3_RELEASE: "z3-4.8.8/z3-4.8.8-x64-ubuntu-16.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache .plt directory
        uses: actions/cache@v2
        with:
          path: .plt
          key: ${{ runner.os }}-otp-${{ matrix.otp }}
      - name: Build submodules
        run: |
          git submodule init && git submodule update
          bash -c "cd lib/gpb && ls build && echo `./build/find-vsn --show-vsn` > gpb.vsn && cat gpb.vsn && ls && cd ../.."
          git submodule foreach make
      - name: Install Z3
        run: bash -x fetch_z3.sh
      - name: Install Python modules
        run: |
          apt-get update
          apt-get install -y python3-pip
          python3 -m pip install --user -r requirements.txt
      - name: Install protobuf library
        run: bash -x fetch_protoc.sh
      - name: Build CutEr
        run: |
          autoconf
          ./configure --with-protoc=$PWD/lib/protoc-3.19.2/bin/protoc
          make depend
          make -j 2
      - name: Run Dialyzer
        run: make dialyzer
      - name: Run unit tests
        run: make utest
      - name: Run functional tests
        run: make ftest
