name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  otps:
    strategy:
      matrix:
        platformn: ubuntu-latest
        otp:
          - "22.3"
          - "21.3"
          - "21.0"
          - "20.3"
    runs-on: ${{ matrix.platform }}
    name: OTP ${{ matrix.otp }}
    container: aggelgian/erlang:${{ matrix.otp }}
    env:
      GPB_ALLOW_NON_CONFORMING_VSN_FORMAT: 1
      Z3_RELEASE: "z3-4.8.14/z3-4.8.14-x64-glibc-2.31"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache .plt directory
        uses: actions/cache@v2
        with:
          path: .plt
          key: ${{ runner.os }}-otp-${{ matrix.otp }}
      - name: Build submodules
        run: |
          bash -c "echo 4.19.5 > lib/gpb/gpb.vsn"
          git submodule foreach make
      - name: Install Z3
        run: bash -x fetch_z3.sh
      - name: Install Python modules
        run: |
          apt-get update
          apt-get install -y python3-pip
          python3 -m pip install --user -r requirements.txt
      - name: Install protobuf library
        run: bash -x fetch_protoc.sh
      - name: Build CutEr
        run: |
          autoconf
          ./configure --with-protoc=$PWD/lib/protoc-3.20.2/bin/protoc
          make depend
          make -j 2
      - name: Run Dialyzer
        run: make dialyzer
      - name: Run unit tests
        run: make utest
      - name: Run functional tests
        run: make ftest
